### ISSUE TITLE
HTML-escaped values in templates

### ISSUE THREAD

**Issue by bilus** [tooploox/oya#34]
```
cat > Oyafile
Project: foo
Values:
  xxx:
    foo: 5
    bar:
      baz: qux
xxx: |
  oya render ./input.txt -o /tmp/out
C-d
mkdir /tmp/out
cat > input.txt
<%= "&&" %>
C-d
oya render input.txt -o /tmp/
cat /tmp/out/input.txt
```

Expected output:
```
&&
```

Actual output:
```
&#34;qux&#34;
```

**Comment by bilus** [comment]
`raw` plush built-in lets you prevent escaping: https://github.com/gobuffalo/plush/blob/master/escape_test.go#L22

Ideas:

1. Make a PR to enable turning off escaping.
2. Call raw to wrap all values in scope before rendering (but not before running in script!).

**Comment by bart84ek** [comment]
I found `html.UnescapeString(result)`to be the easiest solution.
Also saw only `&amp` causing problems. Other chars `!@$%/<>` are not encoded during plush render.

**Comment by bart84ek** [comment]
PR #70
