### ISSUE TITLE
"Oya not optimised for your Mac" message

### ISSUE THREAD

**Issue by magdalenasliwinska** [tooploox/oya#64]
I got following message using `oya run` command on macOS Mojave 10.14.4:
<img width="405" alt="Screenshot 2019-05-30 at 13 15 43" src="https://user-images.githubusercontent.com/43176922/58663736-6d2ddd00-832d-11e9-8879-b97534d4e094.png">

However, it didn't affect the expected result of used command.

**Comment by bart84ek** [comment]
It looks like 32bit oya binary on 64bit machine.
Try to reinstall and if doesn't help i need output of 
```
$ uname -m
$ file `which oya`
```

**Comment by magdalenasliwinska** [comment]
Upgrading oya via `curl https://oya.sh/get | bash` solved the issue.
